#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket

if [ ! -x "${DAEMON}" ]; then
   exit 0
fi

case "$1" in
	start)
		start-stop-daemon --start --quiet --exec $DAEMON -- -d 2>/dev/null
      exit $?
		;;
	stop)
      # Default signal is SIGTERM
		start-stop-daemon --stop --quiet --name $NAME --retry 5
      exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop}" >&2
		exit 1
		;;
esac
